name: jira-reporter-dev

services:
  backend:
    image: ${HARBOR_URL:-x.x.x.x(HARBOR_URL)}/dev/jira-reporter-backend:${TAG:-dev-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BO_BASE_IMAGE:-python:3.12-slim}
        SKIP_SYS_DEPS: ${BO_SKIP_SYS_DEPS:-false}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.org/simple/}
    container_name: jira-backend-dev
    ports:
      - "8010:8000"
    env_file:
      - ./app/secret/.env
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://${APP_DB_USER}:${APP_DB_PASS}@mongo:27017/?authSource=${APP_DB_NAME}
      - APP_DB_NAME=${APP_DB_NAME}
      - PILOT_ENABLED=${PILOT_ENABLED}
    volumes:
      - ./app/secret:/app/app/secret:ro
      - ./data/uploads-dev:/app/uploads

  frontend:
    image: ${HARBOR_URL:-x.x.x.x(HARBOR_URL)}/dev/jira-reporter-frontend:${TAG:-dev-latest}
    build:
      context: .
      dockerfile: frontend/optool/Dockerfile
      args:
        NODE_BASE_IMAGE: ${BO_FE_NODE_BASE_IMAGE:-node:22-alpine}
        NGINX_BASE_IMAGE: ${BO_FE_NGINX_BASE_IMAGE:-nginx:alpine}
        SKIP_NPM_INSTALL: ${BO_FE_SKIP_NPM_INSTALL:-false}
    container_name: jira-frontend-dev
    ports:
      - "9010:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27020:27017"
    volumes:
      - ./data/mongodb-dev:/data/db
      - ./scripts:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express-dev
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
