"""Excel labels corresponding to services/sr-type-fields.ts in the frontend."""

# The editor field is stored in description; other fields live in type_detail.
EDITOR_FIELDS = {
    'IMPROVEMENT': 'improvementDetail', 'BUG_FIX': 'reproduceSteps',
    'DATA_REQUEST': 'dataItems', 'PERMISSION': 'permissionReason',
    'CONFIG_CHANGE': 'changeDetail', 'SERVER_INFRA': 'workDetail',
    'SECURITY': 'securityIssue', 'ETC': 'description',
}
REQUEST_FIELDS = {
    'IMPROVEMENT': ['currentProblem', 'improvementDetail', 'expectedEffect', 'targetMenu', 'referenceCase', 'completionCriteria'],
    'BUG_FIX': ['errorScreen', 'occurredAt', 'errorMessage', 'reproduceSteps', 'expectedResult', 'actualResult', 'userEnvironment'],
    'DATA_REQUEST': ['dataPurpose', 'dataItems', 'dataPeriodFrom', 'dataPeriodTo', 'dataCondition', 'containsPersonalInfo', 'containsSensitiveInfo', 'deliveryFormat', 'deliveryMethod', 'approver', 'retentionDate'],
    'PERMISSION': ['targetUser', 'requestedPermission', 'permissionReason', 'permissionDuration', 'permissionExpiry', 'approver', 'existingPermission'],
    'CONFIG_CHANGE': ['configTarget', 'changeDetail', 'currentValue', 'requestedValue', 'changeReason', 'impactScope', 'applyDatetime', 'serviceInterruption', 'rollbackPlan', 'verificationMethod'],
    'SERVER_INFRA': ['targetServer', 'workType', 'workDetail', 'resourceInfo', 'workDatetime', 'serviceImpact', 'backupRequired', 'verificationMethod'],
    'SECURITY': ['securityRequestType', 'securityIssue', 'riskLevel', 'diagnosisStandard', 'requestedAction', 'actionDeadline', 'evidenceRequired', 'evidenceFormat', 'exceptionApproval'],
    'FIREWALL': ['requestKind', 'environment', 'firewallRules', 'direction', 'purpose', 'duration', 'expiryDate'],
    'BACKOFFICE_EAA': ['researchNumber', 'mappedVmInfo', 'userList', 'etc'],
    'ETC': ['description'],
}

DETAIL_LABELS = {'currentProblem': '현재 문제점',
 'improvementDetail': '개선 요청 내용',
 'expectedEffect': '기대 효과',
 'targetMenu': '관련 화면 / 메뉴',
 'referenceCase': '참고 사례',
 'completionCriteria': '완료 기준',
 'errorScreen': '오류 발생 화면',
 'occurredAt': '발생 일시',
 'errorMessage': '오류 내용',
 'reproduceSteps': '재현 절차',
 'expectedResult': '기대 동작',
 'actualResult': '실제 동작',
 'userEnvironment': '사용자 환경',
 'dataPurpose': '데이터 요청 목적',
 'dataItems': '요청 데이터 항목',
 'dataPeriodFrom': '데이터 기간 (시작)',
 'dataPeriodTo': '데이터 기간 (종료)',
 'dataCondition': '대상 조건',
 'containsPersonalInfo': '개인정보 포함 여부',
 'containsSensitiveInfo': '민감정보 포함 여부',
 'deliveryFormat': '제공 형식',
 'deliveryMethod': '제공 방식',
 'approver': '승인자',
 'retentionDate': '보관 / 파기 예정일',
 'targetUser': '권한 대상자',
 'requestedPermission': '요청 권한',
 'permissionReason': '요청 사유',
 'permissionDuration': '권한 사용 기간',
 'permissionExpiry': '만료일',
 'existingPermission': '기존 권한 여부',
 'configTarget': '설정 대상',
 'changeDetail': '변경 요청 상세 내용',
 'currentValue': '현재 설정값',
 'requestedValue': '변경 요청값',
 'changeReason': '변경 사유',
 'impactScope': '영향 범위',
 'applyDatetime': '적용 희망 일시',
 'serviceInterruption': '서비스 중단 여부',
 'rollbackPlan': '롤백 방안',
 'verificationMethod': '작업 후 확인 방법',
 'targetServer': '대상 서버 / 시스템',
 'workType': '요청 작업 유형',
 'workDetail': '요청 상세',
 'resourceInfo': '리소스 정보',
 'workDatetime': '작업 희망 일시',
 'serviceImpact': '서비스 영향 여부',
 'backupRequired': '사전 백업 필요 여부',
 'securityRequestType': '보안 요청 유형',
 'securityIssue': '취약점 또는 보안 이슈',
 'riskLevel': '위험도',
 'diagnosisStandard': '진단 기준',
 'requestedAction': '조치 요청 내용',
 'actionDeadline': '조치 기한',
 'evidenceRequired': '증적 필요 여부',
 'evidenceFormat': '증적 양식',
 'exceptionApproval': '예외 승인 여부',
 'requestKind': '신청 구분',
 'environment': '적용 환경',
 'firewallRules': '방화벽 정책 목록',
 'sourceIp': '출발지 IP / 대역',
 'sourceHost': '출발지 PC / 서버 이름',
 'destinationIp': '목적지 IP / 대역',
 'destinationHost': '목적지 PC / 서버 이름',
 'portProtocol': '포트 / 프로토콜',
 'portPurpose': '포트 용도',
 'direction': '방향',
 'purpose': '업무 목적',
 'duration': '적용 기간',
 'expiryDate': '만료일',
 'researchNumber': '연구번호',
 'mappedVmInfo': '매핑 VM 정보',
 'userList': '사용자 정보',
 'name': '이름(소속)',
 'email': '이메일 주소',
 'note': '비고',
 'etc': '기타',
 'description': '요청 상세 내용'}

DETAIL_OPTIONS = {'IMPROVEMENT': {},
 'BUG_FIX': {},
 'DATA_REQUEST': {'containsPersonalInfo': {'yes': '포함', 'no': '미포함', 'unknown': '모름'},
                  'containsSensitiveInfo': {'yes': '포함', 'no': '미포함', 'unknown': '모름'},
                  'deliveryFormat': {'csv': 'CSV',
                                     'excel': 'Excel',
                                     'sql': 'SQL 결과',
                                     'api': 'API',
                                     'other': '기타'},
                  'deliveryMethod': {'internal': '내부망 전달',
                                     'permission': '권한 부여',
                                     'encrypted': '암호화 파일',
                                     'other': '기타'}},
 'PERMISSION': {'permissionDuration': {'permanent': '상시', 'temporary': '임시', 'specific': '특정 기간'},
                'existingPermission': {'new': '신규', 'change': '변경', 'revoke': '회수'}},
 'CONFIG_CHANGE': {'serviceInterruption': {'yes': '있음', 'no': '없음', 'unknown': '모름'}},
 'SERVER_INFRA': {'workType': {'create': '서버 생성',
                               'restart': '서버 재기동',
                               'disk': '디스크 증설',
                               'firewall': '방화벽 정책',
                               'ssl': 'SSL 인증서',
                               'deploy': '배포 환경',
                               'db': 'DB 설정',
                               'log': '로그 수집',
                               'other': '기타'},
                  'serviceImpact': {'stop': '서비스 중단', 'delay': '처리 지연', 'none': '무중단'},
                  'backupRequired': {'yes': '필요', 'no': '불필요'}},
 'SECURITY': {'securityRequestType': {'vulnerability': '취약점 조치',
                                      'account': '계정 점검',
                                      'permission_revoke': '권한 회수',
                                      'log_check': '로그 확인',
                                      'other': '기타'},
              'riskLevel': {'high': '상', 'medium': '중', 'low': '하'},
              'evidenceRequired': {'yes': '필요', 'no': '불필요'},
              'exceptionApproval': {'yes': '예외 처리 필요', 'no': '해당 없음'}},
 'FIREWALL': {'requestKind': {'new': '신규 오픈', 'change': '정책 변경', 'delete': '정책 삭제', 'temp': '임시 오픈'},
              'environment': {'production': '운영', 'development': '개발'},
              'direction': {'inbound': '인바운드 (외부 → 내부 트래픽)',
                            'outbound': '아웃바운드 (내부 → 외부 트래픽)',
                            'both': '양방향 (상호 통신)'},
              'duration': {'permanent': '상시', 'temporary': '임시'}},
 'BACKOFFICE_EAA': {},
 'ETC': {}}
