// 자산 Import/Export 템플릿 컬럼 정의 (카테고리별). 순수 데이터.
import { EOS_STATUS_KEY, EOS_DATE_KEY } from 'src/types/assets'
import {
  ANTIVIRUS_KEY, DISPOSAL_KEY, EOL_DATE_KEY, EOL_STATUS_KEY, ISMS_P_KEY, TAGS_KEY, VADA_KEY,
} from './assetKeys'

export type TemplateCol = { key: string; label: string; sample?: string }

export const CATEGORY_TEMPLATE_COLS: Record<string, TemplateCol[]> = {
  '서버': [
    { key: 'asset_id',      label: 'Asset ID (고유키, 재import 시 매칭용)',                            sample: 'SRV-0001' },
    { key: 'ip',            label: 'IP',                                                              sample: '192.168.1.1' },
    { key: 'name',          label: 'HostName',                                                        sample: 'web-server-01' },
    { key: '자산유형',      label: '자산유형(서버 / 네트워크 / DBMS / 정보보호시스템 / VMware)',     sample: '' },
    { key: '구분',          label: '구분',                                                            sample: '물리' },
    { key: '자산번호',      label: '자산번호',                                                        sample: 'SV-001' },
    { key: '자산관리번호',  label: '자산관리번호',                                                    sample: '' },
    { key: 'SN',            label: 'SN',                                                              sample: '' },
    { key: '서버명',        label: '서버명 / 자산명',                                                 sample: '웹서버' },
    { key: '설명',          label: '설명',                                                            sample: '메인 웹서버' },
    { key: '운영체제',      label: '운영체제 / 배포판',                                               sample: 'Rocky Linux' },
    { key: 'version',       label: '버전',                                                            sample: '8.10' },
    { key: '제조사',        label: '제조사',                                                          sample: '' },
    { key: '용도',          label: '용도(상세)',                                                      sample: '' },
    { key: '소속부서',      label: '소속부서/사업',                                                   sample: '' },
    { key: '위치',          label: '위치',                                                            sample: '암빅데이터센터' },
    { key: EOS_STATUS_KEY,  label: 'EoS여부',                                                         sample: '' },
    { key: EOS_DATE_KEY,    label: 'EoS종료일자',                                                     sample: '' },
    { key: EOL_STATUS_KEY,  label: 'EoL여부',                                                         sample: '' },
    { key: EOL_DATE_KEY,    label: 'EoL종료일자',                                                     sample: '' },
    { key: ISMS_P_KEY,      label: 'ISMS-P대상여부',                                                  sample: 'O' },
    { key: 'ISMS-P비고',   label: 'ISMS-P비고',                                                      sample: '' },
    { key: VADA_KEY,        label: 'VADA설치여부',                                                    sample: 'O' },
    { key: 'VADA비고',      label: 'VADA비고',                                                        sample: '' },
    { key: ANTIVIRUS_KEY,   label: '백신여부',                                                        sample: 'O' },
    { key: '백신비고',       label: '백신비고',                                                        sample: '' },
    { key: DISPOSAL_KEY,    label: '폐기여부',                                                        sample: 'O' },
    { key: '폐기일정',      label: '폐기일정',                                                        sample: '' },
    { key: '폐기비고',      label: '폐기 관련 비고',                                                  sample: '' },
    { key: '제품명',        label: '제품명(모델명)',                                                  sample: '' },
    { key: '사양',          label: '사양',                                                            sample: '' },
    { key: '도입사업',      label: '도입사업',                                                        sample: '' },
    { key: '납품회사',      label: '납품회사',                                                        sample: '' },
    { key: '담당자',        label: '담당자',                                                          sample: '' },
    { key: '도입가격',      label: '도입가격',                                                        sample: '' },
    { key: '도입일자',      label: '도입일자(취득일자)',                                              sample: '' },
    { key: '수령일',        label: '수령일',                                                          sample: '2024-01-01' },
    { key: '변경일',        label: '변경일',                                                          sample: '' },
    { key: '변경사항',      label: '변경사항',                                                        sample: '' },
    { key: '유지보수계약구분', label: '유지보수 계약구분',                                             sample: '' },
    { key: '유지보수종료일자', label: '현 유지보수 종료일자',                                          sample: '' },
    { key: '유지보수업체',  label: '유지보수 업체',                                                   sample: '' },
    { key: '유지보수연락처', label: '유지보수 연락처',                                                sample: '' },
    { key: '유지보수특이사항', label: '유지보수 특이사항',                                             sample: '' },
    { key: TAGS_KEY,        label: '태그',                                                            sample: '' },
    { key: '비고',          label: '비고',                                                            sample: '' },
  ],
  '네트워크': [
    { key: 'asset_id',      label: 'Asset ID (고유키, 재import 시 매칭용)',                            sample: 'NW-0001' },
    { key: 'ip',            label: 'IP',                                                              sample: '192.168.1.1' },
    { key: 'name',          label: 'HostName',                                                        sample: 'sw-core-01' },
    { key: '자산유형',      label: '자산유형(서버 / 네트워크 / DBMS / 정보보호시스템 / VMware)',     sample: '' },
    { key: '구분',          label: '구분',                                                            sample: 'Switch' },
    { key: '자산번호',      label: '자산번호',                                                        sample: 'NW-001' },
    { key: '자산관리번호',  label: '자산관리번호',                                                    sample: '' },
    { key: 'SN',            label: 'SN',                                                              sample: '' },
    { key: '서버명',        label: '서버명 / 자산명',                                                 sample: '코어스위치' },
    { key: '설명',          label: '설명',                                                            sample: '' },
    { key: '운영체제',      label: '운영체제 / 기종',                                                 sample: 'Cisco Nexus C93180YC-EX' },
    { key: '제조사',        label: '제조사',                                                          sample: '' },
    { key: '용도',          label: '용도(상세)',                                                      sample: '' },
    { key: '소속부서',      label: '소속부서/사업',                                                   sample: '' },
    { key: '위치',          label: '위치',                                                            sample: '암빅데이터센터' },
    { key: EOS_STATUS_KEY,  label: 'EoS여부',                                                         sample: '' },
    { key: EOS_DATE_KEY,    label: 'EoS종료일자',                                                     sample: '' },
    { key: EOL_STATUS_KEY,  label: 'EoL여부',                                                         sample: '' },
    { key: EOL_DATE_KEY,    label: 'EoL종료일자',                                                     sample: '' },
    { key: ISMS_P_KEY,      label: 'ISMS-P대상여부',                                                  sample: 'O' },
    { key: 'ISMS-P비고',   label: 'ISMS-P비고',                                                      sample: '' },
    { key: '제품명',        label: '제품명(모델명)',                                                  sample: '' },
    { key: '사양',          label: '사양',                                                            sample: '' },
    { key: '도입사업',      label: '도입사업',                                                        sample: '' },
    { key: '납품회사',      label: '납품회사',                                                        sample: '' },
    { key: '담당자',        label: '담당자',                                                          sample: '' },
    { key: '도입가격',      label: '도입가격',                                                        sample: '' },
    { key: '도입일자',      label: '도입일자(취득일자)',                                              sample: '' },
    { key: '수령일',        label: '수령일',                                                          sample: '2024-01-01' },
    { key: '변경일',        label: '변경일',                                                          sample: '' },
    { key: '변경사항',      label: '변경사항',                                                        sample: '' },
    { key: TAGS_KEY,        label: '태그',                                                            sample: '' },
    { key: '비고',          label: '비고',                                                            sample: '' },
  ],
  'DBMS': [
    { key: 'asset_id',      label: 'Asset ID (고유키, 재import 시 매칭용)',                            sample: 'DB-0001' },
    { key: 'ip',            label: 'IP',                                                              sample: '192.168.1.1' },
    { key: 'name',          label: 'HostName',                                                        sample: 'db-server-01' },
    { key: '자산유형',      label: '자산유형(서버 / 네트워크 / DBMS / 정보보호시스템 / VMware)',     sample: '' },
    { key: '구분',          label: '구분',                                                            sample: 'DB' },
    { key: '자산번호',      label: '자산번호',                                                        sample: 'DB-001' },
    { key: '자산관리번호',  label: '자산관리번호',                                                    sample: '' },
    { key: 'SN',            label: 'SN',                                                              sample: '' },
    { key: '서버명',        label: '서버명 / 자산명',                                                 sample: 'DB서버' },
    { key: '설명',          label: '설명',                                                            sample: '' },
    { key: '운영체제',      label: '운영체제 / DB종류',                                               sample: 'MariaDB' },
    { key: 'version',       label: '버전',                                                            sample: '10.6.18' },
    { key: '제조사',        label: '제조사',                                                          sample: '' },
    { key: '용도',          label: '용도(상세)',                                                      sample: '' },
    { key: '소속부서',      label: '소속부서/사업',                                                   sample: '' },
    { key: '위치',          label: '위치',                                                            sample: '암빅데이터센터' },
    { key: EOS_STATUS_KEY,  label: 'EoS여부',                                                         sample: '' },
    { key: EOS_DATE_KEY,    label: 'EoS종료일자',                                                     sample: '' },
    { key: EOL_STATUS_KEY,  label: 'EoL여부',                                                         sample: '' },
    { key: EOL_DATE_KEY,    label: 'EoL종료일자',                                                     sample: '' },
    { key: ISMS_P_KEY,      label: 'ISMS-P대상여부',                                                  sample: 'O' },
    { key: 'ISMS-P비고',   label: 'ISMS-P비고',                                                      sample: '' },
    { key: '제품명',        label: '제품명(모델명)',                                                  sample: '' },
    { key: '사양',          label: '사양',                                                            sample: '' },
    { key: '도입사업',      label: '도입사업',                                                        sample: '' },
    { key: '납품회사',      label: '납품회사',                                                        sample: '' },
    { key: '담당자',        label: '담당자',                                                          sample: '' },
    { key: '도입가격',      label: '도입가격',                                                        sample: '' },
    { key: '도입일자',      label: '도입일자(취득일자)',                                              sample: '' },
    { key: '수령일',        label: '수령일',                                                          sample: '2024-01-01' },
    { key: '변경일',        label: '변경일',                                                          sample: '' },
    { key: '변경사항',      label: '변경사항',                                                        sample: '' },
    { key: TAGS_KEY,        label: '태그',                                                            sample: '' },
    { key: '비고',          label: '비고',                                                            sample: '' },
  ],
  '정보보호시스템': [
    { key: 'asset_id',      label: 'Asset ID (고유키, 재import 시 매칭용)',                            sample: 'SEC-0001' },
    { key: 'ip',            label: 'IP',                                                              sample: '192.168.1.1' },
    { key: 'name',          label: 'HostName',                                                        sample: 'sec-device-01' },
    { key: '자산유형',      label: '자산유형(서버 / 네트워크 / DBMS / 정보보호시스템 / VMware)',     sample: '' },
    { key: '구분',          label: '구분',                                                            sample: 'F/W' },
    { key: '자산번호',      label: '자산번호',                                                        sample: 'SEC-001' },
    { key: '자산관리번호',  label: '자산관리번호',                                                    sample: '' },
    { key: 'SN',            label: 'SN',                                                              sample: '' },
    { key: '서버명',        label: '서버명 / 자산명',                                                 sample: '방화벽' },
    { key: '설명',          label: '설명',                                                            sample: '' },
    { key: '운영체제',      label: '운영체제 / 기종',                                                 sample: 'Secure Gate' },
    { key: '수량',          label: '수량',                                                            sample: '1' },
    { key: '제조사',        label: '제조사',                                                          sample: '한싹' },
    { key: '용도',          label: '용도(상세)',                                                      sample: '' },
    { key: '소속부서',      label: '소속부서/사업',                                                   sample: '' },
    { key: '위치',          label: '위치',                                                            sample: '암빅데이터센터' },
    { key: EOS_STATUS_KEY,  label: 'EoS여부',                                                         sample: '' },
    { key: EOS_DATE_KEY,    label: 'EoS종료일자',                                                     sample: '' },
    { key: EOL_STATUS_KEY,  label: 'EoL여부',                                                         sample: '' },
    { key: EOL_DATE_KEY,    label: 'EoL종료일자',                                                     sample: '' },
    { key: ISMS_P_KEY,      label: 'ISMS-P대상여부',                                                  sample: 'O' },
    { key: 'ISMS-P비고',   label: 'ISMS-P비고',                                                      sample: '' },
    { key: '제품명',        label: '제품명(모델명)',                                                  sample: '' },
    { key: '사양',          label: '사양',                                                            sample: '' },
    { key: '도입사업',      label: '도입사업',                                                        sample: '' },
    { key: '납품회사',      label: '납품회사',                                                        sample: '' },
    { key: '담당자',        label: '담당자',                                                          sample: '' },
    { key: '도입가격',      label: '도입가격',                                                        sample: '' },
    { key: '도입일자',      label: '도입일자(취득일자)',                                              sample: '' },
    { key: '수령일',        label: '수령일',                                                          sample: '2024-01-01' },
    { key: '변경일',        label: '변경일',                                                          sample: '' },
    { key: '변경사항',      label: '변경사항',                                                        sample: '' },
    { key: TAGS_KEY,        label: '태그',                                                            sample: '' },
    { key: '비고',          label: '비고',                                                            sample: '' },
  ],
  'VMware': [
    { key: 'asset_id',      label: 'Asset ID (고유키, 재import 시 매칭용)',                            sample: 'VM-0001' },
    { key: 'ip',            label: 'IP',                                                              sample: '192.168.1.1' },
    { key: 'name',          label: 'HostName',                                                        sample: 'vm-host-01' },
    { key: '자산유형',      label: '자산유형(서버 / 네트워크 / DBMS / 정보보호시스템 / VMware)',     sample: '' },
    { key: '구분',          label: '구분',                                                            sample: 'ESXi' },
    { key: '자산번호',      label: '자산번호',                                                        sample: 'VM-001' },
    { key: '자산관리번호',  label: '자산관리번호',                                                    sample: '' },
    { key: 'SN',            label: 'SN',                                                              sample: '' },
    { key: '서버명',        label: '서버명 / 자산명',                                                 sample: 'VM호스트' },
    { key: '설명',          label: '설명',                                                            sample: '' },
    { key: '운영체제',      label: '운영체제 / 버전',                                                 sample: 'ESXi 8.0' },
    { key: 'version',       label: 'Version',                                                         sample: '8.0' },
    { key: '제조사',        label: '제조사',                                                          sample: '' },
    { key: '용도',          label: '용도(상세)',                                                      sample: '' },
    { key: '소속부서',      label: '소속부서/사업',                                                   sample: '' },
    { key: '위치',          label: '위치',                                                            sample: '암빅데이터센터' },
    { key: EOS_STATUS_KEY,  label: 'EoS여부',                                                         sample: '' },
    { key: EOS_DATE_KEY,    label: 'EoS종료일자',                                                     sample: '' },
    { key: EOL_STATUS_KEY,  label: 'EoL여부',                                                         sample: '' },
    { key: EOL_DATE_KEY,    label: 'EoL종료일자',                                                     sample: '' },
    { key: ISMS_P_KEY,      label: 'ISMS-P대상여부',                                                  sample: 'O' },
    { key: 'ISMS-P비고',   label: 'ISMS-P비고',                                                      sample: '' },
    { key: '제품명',        label: '제품명(모델명)',                                                  sample: '' },
    { key: '사양',          label: '사양',                                                            sample: '' },
    { key: '도입사업',      label: '도입사업',                                                        sample: '' },
    { key: '납품회사',      label: '납품회사',                                                        sample: '' },
    { key: '담당자',        label: '담당자',                                                          sample: '' },
    { key: '도입가격',      label: '도입가격',                                                        sample: '' },
    { key: '도입일자',      label: '도입일자(취득일자)',                                              sample: '' },
    { key: '수령일',        label: '수령일',                                                          sample: '2024-01-01' },
    { key: '변경일',        label: '변경일',                                                          sample: '' },
    { key: '변경사항',      label: '변경사항',                                                        sample: '' },
    { key: '유지보수계약구분', label: '유지보수 계약구분',                                             sample: '' },
    { key: '유지보수종료일자', label: '현 유지보수 종료일자',                                          sample: '' },
    { key: '유지보수업체',  label: '유지보수 업체',                                                   sample: '' },
    { key: '유지보수연락처', label: '유지보수 연락처',                                                sample: '' },
    { key: '유지보수특이사항', label: '유지보수 특이사항',                                             sample: '' },
    { key: TAGS_KEY,        label: '태그',                                                            sample: '' },
    { key: '비고',          label: '비고',                                                            sample: '' },
  ],
}
